language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: VH8G8eXdgm2kz4GGa760Bn6hQVCtvCEJ+sDZkcCSymnTkmhMmTcnrXWY1lw+XDhdl75M1w3yCb/PN0fe1dqDfmPbB/olzVoxMlI7TkE5q7Tt6AT/79B9/pPUdwYpiosNArASfO9mBI4k2zLDOsVGjSNMKCbLr3GpY+ByvoREh9FwGyaOFdKumh9ny90UNL7RNX9E8ec9XNl0N3v/nxnx3oCOnBNaD4Le4Yda/78t3OdT8QlnXZEqUznkH2ckpYqFwQ3kq7snYBH8SiHNatBNDyddXwmUwEV+p5sD4zJOQldtYVOw70XK0I5UasmGV3CP0Cm6EQ8gbGRva3vHb6Upym1X4zWolviJnQTHeJpiGoiK4COMV+zdl0aZY7KgM2l9addEnLnhm0qxfpYPxEoNeCYK+VwT9ykpTe8+KtSvNn6HvFml+TQbw0UaD3JVXSIueUDxpOCp/nX+cIWXI6aAS7B4SJ3KmIGFwlIq/CBiUEWQ537vHy+qPehhO63my8OvmvfRq92gt2LtRVAtzfs4DlouWscT8OBd553fmZsWDENzWc9hQLyT/TrmSe9w5raT5Oahj4k609D+/IcGqeCG2tSLmbltx2ZJkBOM4Jl3j+tj+Jv7sRLM5QvvaMUVVJh7UZBAY5VmWomeAbOT4XHl7t9oIRjTptaPwTSaP0H/DpQ=

  app: boiling-meadow-48827
  on:
    repo: sethjensenbrown/surflist-api
